import type { Transaction } from "./types";

/** Fechas al mediodía UTC para evitar desfaces de día. */
function d(y: number, m: number, day: number) {
  return new Date(Date.UTC(y, m - 1, day, 12, 0, 0)).toISOString();
}

/**
 * Movimientos extraídos de extracto TC ****8002 (abr 2026).
 * Créditos al estado de cuenta (reintegros, pagos) van como ingresos con importe positivo.
 */
export const april2026Card8002Movements: Omit<Transaction, "id">[] = [
  {
    type: "expense",
    amount: 2945,
    currency: "UYU",
    category: "Comida",
    date: d(2026, 4, 7),
    paymentMethod: "credit",
    description: "DLO*PedidosYa Market",
    isPending: false,
  },
  {
    type: "income",
    amount: 95.7,
    currency: "UYU",
    category: "Comida",
    date: d(2026, 4, 7),
    paymentMethod: "credit",
    description: "Reintegro DLO*PedidosYa Market",
    isPending: false,
  },
  {
    type: "expense",
    amount: 45,
    currency: "UYU",
    category: "Comida",
    date: d(2026, 4, 7),
    paymentMethod: "credit",
    description: "DLO*PedidosYa Propina",
    isPending: false,
  },
  {
    type: "expense",
    amount: 72.79,
    currency: "UYU",
    category: "Comida",
    date: d(2026, 4, 7),
    paymentMethod: "credit",
    description: "DLO*PedidosYa Envío",
    isPending: false,
  },
  {
    type: "expense",
    amount: 9.32,
    currency: "USD",
    category: "Entretenimiento",
    date: d(2026, 4, 7),
    paymentMethod: "credit",
    description: "Spotify",
    isPending: false,
  },
  {
    type: "expense",
    amount: 45,
    currency: "UYU",
    category: "Comida",
    date: d(2026, 4, 8),
    paymentMethod: "credit",
    description: "DLO*PedidosYa Propina",
    isPending: false,
  },
  {
    type: "expense",
    amount: 2477,
    currency: "UYU",
    category: "Comida",
    date: d(2026, 4, 8),
    paymentMethod: "credit",
    description: "DLO*PedidosYa Tata P",
    isPending: false,
  },
  {
    type: "expense",
    amount: 20.73,
    currency: "USD",
    category: "Servicios",
    date: d(2026, 4, 8),
    paymentMethod: "credit",
    description: "CLAUDE.AI SUBSCRIPTION",
    isPending: false,
  },
  {
    type: "expense",
    amount: 3000,
    currency: "UYU",
    category: "Servicios",
    date: d(2026, 4, 8),
    paymentMethod: "credit",
    description: "STM",
    isPending: false,
  },
  {
    type: "expense",
    amount: 301,
    currency: "UYU",
    category: "Servicios",
    date: d(2026, 4, 8),
    paymentMethod: "credit",
    description: "UTE",
    isPending: false,
  },
  {
    type: "expense",
    amount: 2762.03,
    currency: "UYU",
    category: "Hogar",
    date: d(2026, 4, 8),
    paymentMethod: "credit",
    description: "SODIMAC WEB (cuota 1/2)",
    isPending: false,
  },
  {
    type: "income",
    amount: 11967.76,
    currency: "UYU",
    category: "Otros",
    date: d(2026, 4, 9),
    paymentMethod: "transfer",
    description: "RECIBO DE PAGO tarjeta ****8002",
    isPending: false,
  },
  {
    type: "income",
    amount: 29.25,
    currency: "UYU",
    category: "Hogar",
    date: d(2026, 4, 10),
    paymentMethod: "credit",
    description: "Ajuste SODIMAC WEB (cuota 1/2)",
    isPending: false,
  },
  {
    type: "expense",
    amount: 2415.54,
    currency: "UYU",
    category: "Otros",
    date: d(2026, 4, 13),
    paymentMethod: "credit",
    description: "Cuota préstamo (IVA) — cuota 5/6",
    isPending: false,
  },
  {
    type: "expense",
    amount: 2450.83,
    currency: "UYU",
    category: "Ropa",
    date: d(2026, 4, 17),
    paymentMethod: "credit",
    description: "BAMBOO *TiendaMia L2 (cuota 3/3)",
    isPending: false,
  },
];
